DSEG	SEGMENT
SUM 	DB 	?
HTAB	DB	'0123456789ABCDEF'
DSEG	ENDS
CSEG 	SEGMENT
	ASSUME 	CS: CSEG, DS: DSEG
START: 	MOV	AX, DSEG
	MOV 	DS, AX
	MOV 	AH, 01H	; INPUT X
	INT 	21H
	SUB 	AL, 30H
	XOR 	AH, AH
	MOV 	CL, 5H
	MUL	CL
	MOV 	BL, AL	; STORE 5X TO BL
	MOV	DL, '*'	; OUTPUT "*5+"
	MOV 	AH, 02H
	INT 	21H
	MOV 	DL, '5'
	INT 	21H
	MOV 	DL, '+'
	INT 	21H
	MOV 	AH, 01H	; INPUT Y
	INT 	21H
	SUB 	AL, 30H
	ADD	BL, AL 
	MOV 	SUM, BL ; NOW WE HAS 5X+Y IN SUM
	MOV	AH, 02H ; OUPUT '='
	MOV 	DL,'='
	INT 	21H
	MOV 	CL, 4	; OUTPUT TENS DIGITS
	MOV	AL, BL
	SHR 	AL, CL
	LEA 	BX, HTAB
	XLAT
	MOV 	DL, AL
	MOV 	AH, 02H
	INT 	21H
	MOV 	AL, SUM ; OUTPUT SINGLE DIGITS
	AND 	AL, 0FH	;
	XLAT	
	MOV 	DL, AL
	MOV 	AH, 02H
	INT	21H
	MOV 	DL, 'H' ; OUPUT 'H'
	INT 	21H
	MOV	AH, 4CH
	INT 	21H
CSEG	ENDS
	END 	START
	
	